language: cpp

jobs:
  include:
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      addons:
        homebrew:
          packages:
            - cmake
            - graphviz
            - doxygen
#   - os: linux
#     dist: bionic
#     compiler: gcc
#     addons:
#       apt:
#         packages:
#           - cmake
#           - graphviz
#           - doxygen

install:
  - echo ${PATH}
  - echo ${CXX}
  - ${CXX} --version
  - cmake --version

branches:
  only:
    - master

script: ./build.sh /tmp/build
